###服务启动端口号
server:
  port: 9003
###服务名称(服务注册到eureka名称)
spring:
  application:
    name: clark-resttemplate
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka,http://localhost:8002/eureka
    register-with-eureka: true
    fetch-registry: true